---
title: "DATA 607 Discussion 11 - Recommender Systems"
author: "RJM"
date: "27/06/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Tasks
1. Analyze an existing recommender system that you find interesting
2. Perform a Scenario Design analysis. Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization’s customers.
3. Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.
4. Include specific recommendations about how to improve the site’s recommendation capabilities going forward.

### Recommender System
I will use LinkedIn as my example for the recommender system.

### Targets
LinkedIn targets professionals and matches their experience, education, and skills to find new networking and job opportunities. The current number of membership stands at over 600 millions and about 39% are paid members. It hosts personal and business webpages along with webpages for interest groups. 

LinkedIn also targets influencers and organizations involved in multiple professional services. A number of non-profit, research-based, and universities use LinkedIn to advance their platforms and increase their followership.

### What are the key goals?
LinkedIn would like to grow its membership and for that purpose it would need to attract potential members from the networks of the current clientele. In order to be more attractive, LinkedIn has to be able to meet the expectations of the professionals that would join it by helping them attain their career and professional goals.

LinkedIn is currently using a very effective strategy through the recommendations of the potential contacts and options of following interest groups. It uses to item-to-item approach where a current search, invite, or an attempt to make a contact yields more recommendations and updates later as other related individuals or organizations become available for contacting.

### How can you help them accomplish those goals?
One of the ideas that comes to mind is for the LinkedIn to make better job recommendations for the individuals. Currently, LinkedIn makes some job recommendations but it seems that this function can be enhanced to really entice people to apply and grow with the platform by pro-actively recommending jobs by picking up key skills and experience areas from members' resumes and profiles.

Another potential improvement area would be to focus on recommending purchases that can help professionals to enhance their learning and skills. These could be recommendations for specialty instruments, courses, computers, etc. LinedID has a great potential to have a market place of its own and it has most of the work in that spectrum carved out by the predecessors. On top of that, it stands at a vantage point with access to professionals with higher incomes. 
 
### Any recommendations for reverse engineering?
A very nimble approach for LinkedIn would be to fine tune its recommendations by creating a wholistic and profile-based approach. It seems that the current recommendations especially for the jobs are generated by the individual member's searches. As mentionaed above, LinkedIn can use the information in the profile or resume to pro-actively recommend jobs. 

It can also use the information from travel interests to recommend jobs in other countries. This can help companies with their global talent hunt. Providing portability advice and help to professionaly to practice in their areas in certain countries could also be provided as a paid service.

### Conclusions
LindedIn is a fairly successful platform but it has many areas of growth that it has not yet tapped into. As mentioned above, creating a marketplace, selling relocation assistance services, professional placements, etc., are just some of those. 

### Resources

1. https://99firms.com/blog/linkedin-statistics/#gref
2. https://towardsdatascience.com/recommender-systems-in-practice-cef9033bb23a


